spring:
  datasource:
    name: defaultdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_DFRI1R-RuPHFzGceYe1@mysql-398af07c-dan2xsanz1978-b788.h.aivencloud.com:15898/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_DFRI1R-RuPHFzGceYe1

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: "true"
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: dlsanz.asi@gmail.com
    password: umvm uben yagx msyc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict
    context-path: /api/
  port: 15898

allowed:
  origin: http://localhost:3000

app:
  product-image-path: C:\Users\danle\Documents\Image
  account-image-path: C:\Users\danle\Documents\Image

